apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: manu-vi
    serving.kserve.io/deploymentMode: ModelMesh
  labels:
    name: manu-vi
    opendatahub.io/dashboard: "true"
  name: manu-vi
  namespace: manuela-visual-inspection
spec:
  predictor:
    model:
      modelFormat:
        name: onnx
        version: "1"
      runtime: manu-vi
      storage:
        key: aws-connection-manu-vi
        path: manu-vi-best.onnx