apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: manuela-visual-inspection
  namespace: manuela-visual-inspection
spec:
  params:
    - default: 1.0.0
      name: IMAGE_TAG
      type: string
    - default: quay.io/manuela/cam-sim
      name: IMAGE_NAME
      type: string
    - default: 'https://github.com/stefan-bergstein/manuela-visual-inspection.git'
      name: GIT_REPO
      type: string
    - default: main
      name: GIT_BRANCH
      type: string
    - default: cam
      name: CONTEXT_DIR
      type: string
    - name: CONTAINERFILE
      type: string    
      default: Containerfile   
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: ''
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: ''
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:16b8e98aa03a874dfc0fd16cd4aaaeea193dc60882c61653e768f8f503fe33e3
        - name: userHome
          value: /home/git
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: buildah
      params:
        - name: IMAGE
          value: '$(params.IMAGE_NAME):$(params.IMAGE_TAG)'
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:bafb452c5346d8517d94639efa90e8d6d72cd11e45d49369c3d9305784d1c3f6
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: $(params.CONTAINERFILE)
        - name: CONTEXT
          value: $(params.CONTEXT_DIR)
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
        - name: BUILD_EXTRA_ARGS
          value: ''
        - name: PUSH_EXTRA_ARGS
          value: ''
        - name: SKIP_PUSH
          value: 'false'
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: workspace
  workspaces:
    - name: workspace
