apiVersion: v1
kind: ConfigMap
metadata:
  name: cam-sim-conf
data:
  BOOTSTRAP_SERVER: manu-vi-kafka-bootstrap:9092
#  BOOTSTRAP_SERVER: 	manu-vi-kafka-bootstrap-manuela-visual-inspection.apps.ocp5.stormshift.coe.muc.redhat.com:443
#  SECURITY_PROTOCOL: SSL
#  SSL_CAFILE: /mnt/kafka-ca-cert/kafka-ca.crt
  FPS: '0.1'
  CAMID: '0'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cam-sim
  labels:
    app: visual-inspection
    app.kubernetes.io/part-of: visual-inspection
spec:
  selector:
    matchLabels:
      app: cam-sim
  replicas: 1
  template:
    metadata:
      labels:
        app: cam-sim
    spec:
      containers:
        - name: cam-sim
          image: quay.io/manuela/cam-sim:1.0.0
#          image: cam-sim:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: cam-sim-conf
#            - configMapRef:
#                name: kafka-ca-cert
#          volumeMounts:
#            - name: kafka-ca-cert-volume
#              mountPath: /mnt/kafka-ca-cert
#      volumes:
#        - name: kafka-ca-cert-volume
#          configMap:
#            name: kafka-ca-cert
#            defaultMode: 420
      restartPolicy: Always
