kind: Kafka
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: manu-vi
  namespace: manuela-visual-inspection
spec:
  kafka:
    version: 3.5.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: '3.5'
      message.max.bytes: 536870912
      replica.fetch.max.bytes: 536870912
      replica.fetch.response.max.bytes: 536870912
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
