kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: image-processor
  labels:
    component: image-processor
spec:
  lookupPolicy:
    local: true
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: visual-inspection
    component: image-processor
  name: image-processor
spec:
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
    type: Docker
  source:
    contextDir: image-processor
    git:
      uri: https://github.com/stefan-bergstein/manuela-visual-inspection.git
    type: Git
  output:
    to:
      kind: ImageStreamTag
      name: image-processor:cpu
  runPolicy: Serial
  triggers:
  - type: ConfigChange
  successfulBuildsHistoryLimit: 3
  postCommit: {}
  resources: {}